o.words={'xxadxx' 'xahx' 'xamx' 'xanx' 'xasx' 'xatx' 'xaxx' 'xbex' 'xbox' 'xbyx' 'xcax' 'xdox' ...
'xehx' 'xelx' 'xerx' 'xexx' 'xfax' 'xgox' 'xhax' 'xhex' 'xhix' 'xhox' 'xifx' 'xinx' 'xisx' 'xitx' ...
'xlox' 'xmax' 'xmex' 'xmix' 'xmux' 'xmyx' 'xnox' 'xofx' 'xohx' 'xokx' 'xonx' 'xopx' 'xorx' 'xowx' ...
'xoxx' 'xpax' 'xpix' 'xrex' 'xsix' 'xsox' 'xtax' 'xtox' 'xupx' 'xusx' 'xwex' 'xyex'};
% Not sure, but I think the source is English Lexicon Project.
% I removed all words with capital letters.
% http://elexicon.wustl.edu/default.asp

