o.words={'ad' 'ah' 'am' 'an' 'as' 'at' 'ax' 'be' 'bo' 'by' 'ca' 'do' ...
'eh' 'el' 'er' 'ex' 'fa' 'go' 'ha' 'he' 'hi' 'ho' 'if' 'in' 'is' 'it' ...
'lo' 'ma' 'me' 'mi' 'mu' 'my' 'no' 'of' 'oh' 'ok' 'on' 'op' 'or' 'ow' ...
'ox' 'pa' 'pi' 're' 'si' 'so' 'ta' 'to' 'up' 'us' 'we' 'ye'};
% Not sure, but I think the source is English Lexicon Project.
% I removed all words with capital letters.
% http://elexicon.wustl.edu/default.asp

